DROP TABLE `PET_BRAG` IF EXISTS;
CREATE TABLE `PET_BRAG`(
    `PET_BRAG_IDX`                 BIGINT   NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `MEMBER_IDX`                   BIGINT   NOT NULL,
    `FILE_IDX`                     BIGINT   NOT NULL COMMENT '대표이미지',
    `ONE_LINE_INTRODUCTION`        VARCHAR  NOT NULL,
    `EXPLANATION`                  VARCHAR  NOT NULL,
    `WORLD_CUP_PARTICIPATION_FLAG` CHAR     NOT NULL DEFAULT 'N',
    `HIT`                          INT      NOT NULL DEFAULT 0,
    `REGISTER_DATE`                DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `UPDATE_DATE`                  DATETIME NULL,
    `REPORT_FLAG`                  CHAR     NOT NULL DEFAULT 'N',
    `DELETE_FLAG`                  CHAR     NOT NULL DEFAULT 'N'
);

DROP TABLE `PET_BRAG_THEME` IF EXISTS;
CREATE TABLE `PET_BRAG_THEME`(
    `PET_BRAG_IDX` BIGINT       NOT NULL,
    `THEME_CODE`   VARCHAR(255) NOT NULL
);

DROP TABLE `THEME` IF EXISTS;
CREATE TABLE `THEME`(
    `THEME_CODE` VARCHAR NOT NULL PRIMARY KEY,
    `THEME_NAME` VARCHAR NOT NULL
);

DROP TABLE `WORLD_CUP_SEASON` IF EXISTS;
CREATE TABLE `WORLD_CUP_SEASON`(
    `SEASON_CODE`       VARCHAR  NOT NULL PRIMARY KEY,
    `SEASON_NAME`       VARCHAR  NOT NULL,
    `SEASON_START_DATE` DATETIME NOT NULL,
    `SEASON_END_DATE`   DATETIME NOT NULL
);

DROP TABLE `PET_WORLD_CUP` IF EXISTS;
CREATE TABLE `PET_WORLD_CUP`(
    `PET_WORLD_CUP_IDX` BIGINT  NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `SEASON_CODE`       VARCHAR NOT NULL,
    `PET_BRAG_IDX`      BIGINT NULL COMMENT '우승IDX'
);

DROP TABLE `PET_WORLD_CUP_HISTORY` IF EXISTS;
CREATE TABLE `PET_WORLD_CUP_HISTORY`(
    `PET_WORLD_CUP_HISTORY_IDX` BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `MEMBER_IDX`                BIGINT NULL
);

DROP TABLE `PET_WORLD_CUP_PROGRESS_HISTORY` IF EXISTS;
CREATE TABLE `PET_WORLD_CUP_PROGRESS_HISTORY`(
    `PET_WORLD_CUP_HISTORY_IDX` BIGINT NOT NULL,
    `CANDIDATE_LEFT`            BIGINT NOT NULL COMMENT '반려동물자랑IDX',
    `CANDIDATE_RIGHT`           BIGINT NOT NULL COMMENT '반려동물자랑IDX',
    `SELECT_IDX`                BIGINT NULL,
    `COMPETE_GROUP`             INT    NOT NULL COMMENT '64강',
    `COMPETE_COUNT`             INT    NOT NULL COMMENT '64강에서 32강을 가려면 32번의 대진이 필요'
);
